### PR TITLE
fix 188 - Type replacement should apply to static parameter types

### PR DESCRIPTION
**Pull request by dsyme**
Fix https://github.com/fsprojects/FSharp.TypeProviders.SDK/issues/188

### CODE REVIEW

**Comment by Thorium** [comment]
After the latest changes my type provider fails for:

FSC: error FS3047: Unknown static argument kind 'MyProject.MyEnum' when resolving a reference to a provided type or method 'MyProvider,MyEnumParam="1"'

error FS1109: A reference to the type 'MyProvider,MyEnumParam="1"' in assembly 'MyProject' was found, but the type could not be found in that assembly

Here, MyProject.MyEnum is a non-design-time enum that is a static parameter for the type provider constructor.

**Comment by dsyme** [comment]
@Thorium could you point me to the code for the type provider please?

**Comment by dsyme** [comment]
@Thorium I can see the problem, will fix it and add more tests, thanks

**Comment by Thorium** [comment]
This is now working with the latest changeset.

**Pull request merged**
