### PR TITLE
Add Get custom attribute fails test

### PR DESCRIPTION
**Pull request by 7sharp9**

### CODE REVIEW

**Comment by 7sharp9** [comment]
Fixes #240

**Comment by 7sharp9** [comment]
ping?

**Comment by dsyme** [comment]
Do you know why the test is failing?  master seems to be passing

>C:\projects\fsharp-typeproviders-sdk\examples\BasicProvider.Tests\BasicProvider.Tests.fs(23,20): error FS3033: The type provider 'ProviderImplementation.BasicGenerativeProvider' reported an error: Could not open file for writing (binary mode): > C:\Users\appveyor\AppData\Local\Temp\1\tmpD260.dllSystem.IO.IOException: The process cannot access the file 'C:\Users\appveyor\AppData\Local\Temp\1\tmpD260.dll' because it is being used by another process.   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)   at ProviderImplementation.ProvidedTypes.BinaryWriter.writeBinaryAndReportMappings[a,b,c,d,e](String outfile, ILGlobals ilg, FSharpOption`1 pdbfile, a portablePDB, Boolean embeddedPDB, b embedAllSource, c embedSourceList, d sourceLink, Boolean emitTailcalls, Boolean deterministic, Boolean showTimes, e dumpDebugInfo, ILModuleDef modul) [C:\projects\fsharp-typeproviders-sdk\examples\BasicProvider.Tests\BasicProvider.Tests.fsproj]

**Comment by 7sharp9** [comment]
@dsyme Hmm Im using `GenerativePropertyProviderWithStaticParams` in my teats and its locking a temp dll?  Test passes for me when I run it in rider with the others though.

**Comment by dsyme** [comment]
Thanks for this!

**Comment by ovatsus** [comment]
After I update to this version, I start to get a lot of warnings like this: `The instantiation of the generic type 'Attributes' is missing and can't be inferred from the arguments or return type of this member. Consider providing a type instantiation when accessing this type, e.g. 'Attributes<_>'`

**Comment by dsyme** [comment]
@ovatsus OK, thanks, I'll get it fixed and add warnaserror

**Pull request merged**
