### PR TITLE
Fix for #230

### PR DESCRIPTION
**Pull request by 7sharp9**

### CODE REVIEW

**Comment by dsyme** [comment]
@7sharp9 Could you add a test as well?

**Comment by 7sharp9** [comment]
I'll see if I can find a bit of time today to write a test to exercise the addition

**Comment by dsyme** [comment]
@7sharp9 Any luck with the testing?  If it turns out really hard to test we can merge, but it would be really great to get a test added, e.g. to keep this working if we ever rewrite the SDK again

**Comment by 7sharp9** [comment]
@dsyme Sorry I never had time yesterday _debugging quotation splicing_
I'll see if I can make a test today if I can.

**Comment by 7sharp9** [comment]
Im struggling with the tests, the size of providedtypes.fs make working with it really tough, vs4mac, ionize and rider all crawl to a halt.

Im also having trouble with making a test, I get a:
```
The design-time type 'System.Collections.Generic.List`1[System.Object]' utilized by a type provider was not found in the target reference assembly set 
```
And Im not sure where this is coming from as vs4mac terminates as I try to debug.

**Comment by 7sharp9** [comment]
@dsyme Is there some sort of assembly redirects thats not happening in tryGetTypeFromAssembly?

```
The design-time type 'System.Collections.Generic.List`1[System.Object]' utilized by a type provider was not found in the target reference assembly set '[tgt assembly mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;\n tgt assembly FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a;\n tmp6qXu1e]'. You may be referencing a profile which contains fewer types than those needed by the type provider you are using.
```

**Pull request closed without merging**
